package com.taskmanagement.util;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

public class PdfGenerator {

    public static ByteArrayInputStream generateReport(
            long totalProjects,
            long totalTasks,
            long completedTasks,
            long pendingTasks,
            long highPriority,
            long mediumPriority,
            long lowPriority
    ) {

        Document document = new Document();

        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);

            document.open();

            Font title =
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);

            Font heading =
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);

            Font normal =
                    FontFactory.getFont(FontFactory.HELVETICA, 12);

            document.add(new Paragraph("TASK MANAGEMENT REPORT", title));

            document.add(new Paragraph(
                    "Generated On : " + LocalDate.now(), normal));

            document.add(new Paragraph(" "));

            // =========================
            // PROJECT SUMMARY
            // =========================

            document.add(new Paragraph("Project Summary", heading));

            document.add(new Paragraph(
                    "Total Projects : " + totalProjects, normal));

            document.add(new Paragraph(" "));

            // =========================
            // TASK SUMMARY
            // =========================

            document.add(new Paragraph("Task Summary", heading));

            document.add(new Paragraph(
                    "Total Tasks : " + totalTasks, normal));

            document.add(new Paragraph(
                    "Completed Tasks : " + completedTasks, normal));

            document.add(new Paragraph(
                    "Tasks Not Yet Started : " + pendingTasks, normal));

            document.add(new Paragraph(" "));

            // =========================
            // PRIORITY SUMMARY
            // =========================

            document.add(new Paragraph("Priority Summary", heading));

            document.add(new Paragraph(
                    "High Priority : " + highPriority, normal));

            document.add(new Paragraph(
                    "Medium Priority : " + mediumPriority, normal));

            document.add(new Paragraph(
                    "Low Priority : " + lowPriority, normal));

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Generated by Task Management System"));

            document.close();

        } catch (Exception e) {

            e.printStackTrace();

        }

        return new ByteArrayInputStream(out.toByteArray());

    }

}